### PR TITLE
Design Documents - Revision 1

### PR DESCRIPTION
**Pull request by ChristopherMcDonald**
High Level Design
- [x] 1. Missing supporting material.
- [x] 2. Missing likely/unlikely changes.
- [x] 3. Missing assumptions.
- [x] 4. The shooting model, shot optimizer and shot recommendation require mathematical model or an equation to explain their behavior (as per rubric).
- [x] 5. In figure 3, should the system also be feeding information back to some of the subsystems?
- [x] 6. In the next version, include the logic/rationale behind methods or techniques you use in your design, how you plan to achieve them, and why they are correct. For example, I get why detecting the ball bouncing off the table would work and how you would go about it, but someone who isn't familiar with your project would have some questions about how it works.
- [x] 7. In the next version, explain why reinforcement learning will work in this situation
- [x] 8. Did you miss a degree of freedom to input to the shooting model? It looks like you give the angular velocity as a scalar, which does not indicate the plane in which the ball will rotate. It seems like you should give it an angle from 0 to 360, indicating how the shooting wheel will be positioned to achieve spin in the desired spin. (Eg. 0 has the wheel at the bottom, spinning straight up and down. At 90, it would be spinning left to right).
- [x] 9. Once you fully figure out how everything will work, explain how you will control angular velocity  independently of the speed of the ball,
- [x] 10. list the main specs of the motor. someone with a print out can’t click a link

Component
- [x] 11. The component design document should have been built upon the high level system design document (I believed it was obvious since you included a lot of low level design in your draft system design). Instead it seems that you've removed a large chunk of your previous document, and many relevant parts are now missing.
- [x] 12. Missing assumptions. Missing supporting material, in this case, the supporting material could be rules and regulations that would dictate the assumptions.
- [x] 13. missing anticipated/likely changes, missing exception/error identification and handling
- [ ] 14. Missing models and mathematical derivations of control parameters for the shooter. For example, how fast should you turn the motor for a desired shot or spin? How
- [x] 15. A few general comments: People (the judges) will be more impressed with your project if you can automatically position all degrees of freedom of the shooter. It would also be good if you could show that you are able to consistently shoot the balls to most locations in the same way, especially because you plan on using machine learning and recommended shots to train the user
- [x] 16. You should add a requirement traceability matrix

### CODE REVIEW

**Comment by ChristopherMcDonald** [comment]
4) I don't wanna
5) It does, the lines from SS go into others and eventually come back to SS. Also true for others.

**Comment by ChristopherMcDonald** [comment]
6. I think I handled this, explained the SR and CV

**Comment by ChristopherMcDonald** [comment]
9. we won't...
10. @pateljd2 can you handle this? You can use a latex table generator and send me it if you want

**Comment by pateljd2** [comment]
im on it ^

**Comment by pateljd2** [comment]
check it out let me know if you have any changes

**Comment by ChristopherMcDonald** [comment]
@pateljd2 looks good to me!

**Comment by ChristopherMcDonald** [comment]
11. will do as last commit, combine documents.
12. ???
13. will handle now, the error / exception handling that is. The other item is in the high level design.
14. @nishp763 do we have some calculations for this? I remember you doing some preliminary research
15. will do
16. I don't want to do this... we will see.

**Comment by ChristopherMcDonald** [comment]
https://github.com/ChristopherMcDonald/SoftwareTronCapstone/pull/69/commits/ea52dcb01cc9bc634360c821ba6140d00a950ed6 handles item 13.

**Comment by ChristopherMcDonald** [comment]
TODOs:
- introduce some math for shooting
- merge documents

**Pull request merged**
