### PR TITLE
Hazard Analysis - Rev 1

### PR DESCRIPTION
**Pull request by ChristopherMcDonald**
## Feedback
- [x] 1. Missing supporting material.
- [x] 2. You say that the system is assumed to be working properly. It is important to consider what kind of failures could cause harm. Are these failures likely to occur? How can the system fail in a dangerous way?
- [x] 3. Maybe require users to remove all loose articles of clothing/jewelry to avoid risk
- [x] 4. State any assumptions you are making about the use of your system and the way it operates. Without assumptions constraining the use of your system, it is easy to imagine ways it could fail and cause hazards.

### CODE REVIEW

**Comment by ChristopherMcDonald** [comment]
So for 1, I am going to send an email asking what to include. The rubric says supporting material is "appendices... etc.", so not much help.

For 3, I can't see why this is here... We say, "The user must be warned not to wear such appendages when using this system" in our mitigation plan. Ignoring this one.

For 4, same deal. We say, "Intentional misuse or destruction of the system will not be discussed as it is outside the scope of this document. The user is assumed to be using fully-functioning and maintained equipment including the table tennis balls, table and paddles. All electrical equipment is assumed to be working at production performance which includes all electrical wiring, components, boards and motors."

**Comment by platkis** [comment]
Also keeping in mind:

- [ ] 5. Add student numbers to front page
- [ ] 6. Subsystem/Component Description: other than providing a short explanation of the component, you can refer to your system design document (your subsystem/components will need to be indexed for quick reference, similar to requirements or hazards).
- [ ] 7. When providing information regarding the document scope, remember the rule of thumb: write it as if your work is not aimed at the TAs or the professor, but third parties who are not familiar with the project. 

(Think we're good for 7, not sure about 6)

**Comment by ChristopherMcDonald** [comment]
for 6, we have a link in section 2.1 :)
for 7, I think we are good as well.

for 5, I gotta do work to make it look good :'(

**Comment by ChristopherMcDonald** [comment]
@platkis can you review this?

**Pull request merged**
